"""
Parameter Optimization — AI suggests trading parameter adjustments.

CRITICAL RULE: Suggestions are NEVER auto-applied.
They are:
1. Generated by AI based on performance data
2. Stored in the database
3. Surfaced in the UI for human review
4. Applied only after operator approval via API

This prevents AI from silently degrading system behavior.
"""
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.core.config import settings
from src.core.logging import get_logger
from src.core.redis_client import Cache
from .ai_engine import AIEngine, get_ai_engine

logger = get_logger(__name__)

_cache = Cache("ai:optimizer", default_ttl=3600)  # Only run once per hour max

SYSTEM_PROMPT_PATH = Path(__file__).parent / "prompts" / "optimizer_prompt.txt"

# Safe bounds — AI can never suggest values outside these ranges
PARAMETER_BOUNDS = {
    "slippage_limit_pct": (0.005, 0.05),
    "entry_threshold": (0.01, 0.15),
    "max_position_size_usdc": (10.0, 500.0),
    "cooldown_seconds": (30, 7200),
    "copy_trade_size_pct": (0.03, 0.30),
}


def _load_system_prompt() -> str:
    try:
        return SYSTEM_PROMPT_PATH.read_text()
    except FileNotFoundError:
        return "Analyze performance and suggest parameter changes. Return JSON."


def _validate_suggestion(suggestion: Dict[str, Any]) -> bool:
    """Ensure AI suggestion is within safe bounds before presenting to operator."""
    param = suggestion.get("parameter")
    value = suggestion.get("suggested_value")

    if param not in PARAMETER_BOUNDS:
        logger.warning("optimizer_unknown_parameter", parameter=param)
        return False

    lo, hi = PARAMETER_BOUNDS[param]
    if not (lo <= value <= hi):
        logger.warning("optimizer_out_of_bounds", parameter=param, value=value, bounds=(lo, hi))
        return False

    return True


async def suggest_optimizations(
    performance_data: Dict[str, Any],
    current_params: Dict[str, Any],
    engine: Optional[AIEngine] = None,
) -> Dict[str, Any]:
    """
    Generate parameter optimization suggestions based on recent performance.

    Args:
        performance_data: Dict with recent_trades, win_rate_by_strategy,
                         avg_slippage, pnl_trend, market_regime
        current_params: Dict of current parameter values
        engine: AI engine (uses singleton if None)

    Returns:
        Dict with suggestions list, overall_assessment, priority.
        Suggestions are filtered through bounds validation.
        Returns empty suggestions if AI unavailable (do not auto-tune without AI).
    """
    if engine is None:
        engine = get_ai_engine()

    if not engine.is_available:
        return {
            "suggestions": [],
            "overall_assessment": "AI unavailable — parameter optimization requires AI assistance.",
            "priority": "low",
            "_fallback": True,
        }

    user_prompt = _build_optimizer_prompt(performance_data, current_params)

    result, _ = await engine.complete(
        system_prompt=_load_system_prompt(),
        user_prompt=user_prompt,
        component="parameter_optimizer",
        context={"current_params": current_params, "trade_count": len(performance_data.get("recent_trades", []))},
        cache=_cache,
        parse_json=True,
        fallback={"suggestions": [], "overall_assessment": "Optimization failed.", "priority": "low"},
    )

    if not result:
        return {"suggestions": [], "overall_assessment": "Optimization failed.", "priority": "low"}

    # Safety validation — filter any out-of-bounds suggestions
    raw_suggestions = result.get("suggestions", [])
    valid_suggestions = [s for s in raw_suggestions if _validate_suggestion(s)]
    skipped = len(raw_suggestions) - len(valid_suggestions)

    if skipped > 0:
        logger.warning("optimizer_suggestions_filtered", skipped=skipped, total=len(raw_suggestions))

    result["suggestions"] = valid_suggestions
    result["_validated"] = True
    result["_suggestions_skipped"] = skipped
    result["generated_at"] = datetime.now(timezone.utc).isoformat()
    result["status"] = "pending_review"  # Always starts as pending — never auto-applied

    return result


def _build_optimizer_prompt(performance_data: Dict[str, Any], current_params: Dict[str, Any]) -> str:
    trades = performance_data.get("recent_trades", [])
    win_rates = performance_data.get("win_rate_by_strategy", {})
    pnl_trend = performance_data.get("pnl_trend", [])

    return f"""PARAMETER OPTIMIZATION REQUEST:

CURRENT PARAMETERS:
{json.dumps(current_params, indent=2)}

PERFORMANCE SUMMARY:
- Recent trades analyzed: {len(trades)}
- PnL trend (last 10): {pnl_trend[-10:] if pnl_trend else 'N/A'}
- Win rate by strategy: {json.dumps(win_rates, indent=2)}
- Average slippage: {performance_data.get('avg_slippage_pct', 'N/A')}
- Market regime: {performance_data.get('market_regime', 'unknown')}

ALLOWED PARAMETER RANGES:
{json.dumps(PARAMETER_BOUNDS, indent=2)}

Analyze the performance and suggest parameter adjustments within allowed bounds.
Return your JSON suggestions."""
